class IdButtons:
    TABLE_EXPLORE = "table-explore"
    NV_NORMALIZE = "nv_normalize"
    OUTDOOR_COMFORT_NORMALIZE = "outdoor-comfort-normalize"
    TABLE_TMP_RH = "table-tmp-rh"

    DAILY_ROSE_CHART = "daily-rose-chart"
    CLIMATE_PROFILES_CHART = "climate-profiles-chart"
    PSYCHROMETRIC_CHART_CHART = "Psychrometric-Chart-chart"
    CUSTOM_ROSE_CHART = "custom-rose-chart"
    HDD_CDD_CHART = "hdd-cdd-chart"

    MORE_CHARTS_LABEL = "more-charts-label"
    DOWNLOAD_BUTTON_LABEL = "download-button-label"
    CUSTOM_HEATMAP_CHART_LABEL = "custom-heatmap-chart-label"

    EXPLORE_YEARLY_CHART_LABEL = "explore-yearly-chart-label"
    EXPLORE_DAILY_CHART_LABEL = "explore-daily-chart-label"
    EXPLORE_HEATMAP_CHART_LABEL = "explore-heatmap-chart-label"
    NATURAL_VENTILATION_LABEL = "natural-ventilation-label"
    UTCI_CHARTS_LABEL = "utci-charts-label"
    SUN_PATH_CHART_LABEL = "sun-path-chart-label"
    DAILY_CHART_LABEL = "daily-chart-label"
    MONTHLY_CHART_LABEL = "monthly-chart-label"
    CLOUD_CHART_LABEL = "cloud-chart-label"
    YEARLY_CHART_LABEL = "yearly-chart-label"
    HEATMAP_CHART_LABEL = "heatmap-chart-label"
    WIND_ROSE_LABEL = "wind-rose-label"
