name: Cypress 🌲 
on: [push, pull_request]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Clima
        run: |-
          pip install pipenv
          pipenv install

      - name: Start Clima
        run: |-
          pipenv run python main.py &

      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'

      - name: Install Cypress
        run: |-
          cd tests/node
          npm ci

      - name: Run Cypress
        run: |-
          npx cypress run 